version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: 'Library\Properties\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
build:
  project: FloatingStatusWindow.sln
  verbosity: minimal
after_build:
- cmd: nuget pack FloatingStatusWindow.nuspec -Version %appveyor_build_version% -Properties Configuration=Release -OutputDirectory bin\Release\
artifacts:
- path: Library\bin\$(configuration)\FloatingStatusWindow.*.nupkg
  name: NuGet
deploy:
- provider: Environment
  name: GitHub
- provider: Environment
  name: NuGet
install:
- cmd: git submodule update --init --recursive